# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('starting_price', models.FloatField()),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('open', 'Open'), ('cancelled', 'Cancelled'), ('cancelled-no-bids', 'Cancelled due to no bids'), ('waiting-for-payment', 'Waiting for payment'), ('waiting-to-ship', 'Waiting to ship'), ('shipped', 'Shipped'), ('finished', 'Finished')], default='preview', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('open_until', models.DateTimeField(blank=True, default=None, null=True)),
                ('ended_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('rejected', 'Rejected')], default='active', max_length=50)),
                ('placed_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField()),
                ('arrived_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('tracking_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('shipping', 'Shipping'), ('returning', 'Returning'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='shipping', max_length=50)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.Auction')),
            ],
        ),
    ]
