# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('starting_price', models.FloatField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('finished', 'Finished'), ('cancelled', 'cancelled')], default='open', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ended_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('rejected', 'Rejected')], default='active', max_length=50)),
                ('placed_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
