# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('preview', 'Preview'), ('open', 'Open'), ('finished', 'Finished'), ('cancelled', 'cancelled')], default='preview', max_length=50),
        ),
    ]
