# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20171109_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='product',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
