# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_charity_logo'),
        ('auction', '0003_auto_20171115_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_received', models.DateTimeField(blank=True, default=None, null=True)),
                ('item_sent', models.DateTimeField(blank=True, default=None, null=True)),
                ('tracking_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('waiting-for-payment', 'Waiting For Payment'), ('received-payment', 'Received Payment'), ('item-shipped', 'Item Shipped')], default='waiting-for-payment', max_length=50)),
                ('note', models.TextField()),
                ('auction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.Auction')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.Product')),
            ],
        ),
    ]
