# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20171027_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='open_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
