# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20171115_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='stripe_charge_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
