# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_sale_stripe_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='active', max_length=50),
        ),
    ]
