# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20171115_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('waiting-for-payment', 'Waiting For Payment'), ('received-payment', 'Received Payment'), ('item-shipped', 'Item Shipped'), ('cancelled', 'Cancelled')], default='waiting-for-payment', max_length=50),
        ),
    ]
