# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20171115_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cheque_sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_received_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
