# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_auto_20171123_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
