# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Auction = apps.get_model('auction', 'Auction')
    auctions = Auction.objects.all().select_related('product__donor')
    for auction in auctions:
        donor = auction.product.donor
        charity = donor.charities.first()
        if charity:
            auction.charity = charity
            auction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_remove_donor_charity'),
        ('auction', '0011_bid_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='charity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Charity'),
        ),
        migrations.RunPython(forwards),
    ]
