POST_VISIBILITY_PUBLIC = 'public'
POST_VISIBILITY_PROTECTED = 'protected'
POST_VISIBILITY_PRIVATE = 'private'

POST_VISIBILITY_CHOICES = (
    (POST_VISIBILITY_PUBLIC, 'Public'),
    (POST_VISIBILITY_PROTECTED, 'Protected'),
    (POST_VISIBILITY_PRIVATE, 'Private'),
)

COMMENT_STATUS_PUBLIC = 'public'
COMMENT_STATUS_REVIEW = 'review'
COMMENT_STATUS_FLAGGED = 'flagged'

COMMENT_STATUS_CHOICES = (
    (COMMENT_STATUS_PUBLIC, 'Public'),
    (COMMENT_STATUS_REVIEW, 'Review'),
    (COMMENT_STATUS_FLAGGED, 'Flagged'),
)
