# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('storage', '0002_auto_20171020_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('logo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.Medium')),
            ],
            options={
                'verbose_name_plural': 'Charities',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('company', 'Company'), ('celebrity', 'Celebrity'), ('other', 'Other')], max_length=50)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Charity')),
                ('logo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_having_as_logo', to='storage.Medium')),
                ('video', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_having_as_video', to='storage.Medium')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Medium')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tagging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Tag')),
            ],
        ),
    ]
