# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Charities',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('company', 'Company'), ('celebrity', 'Celebrity'), ('other', 'Other')], max_length=50)),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
                ('charity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.Charity')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('charge_tax', models.BooleanField(default=False)),
                ('requires_shipping', models.BooleanField(default=False)),
                ('weight_unit', models.CharField(choices=[('oz', 'oz'), ('lb', 'lb'), ('kg', 'kg'), ('g', 'g')], default='kg', max_length=10)),
                ('weight', models.FloatField(default=0)),
                ('hs_tariff_code', models.CharField(default=None, max_length=50, null=True)),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.Donor')),
            ],
        ),
    ]
