# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='charity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.Charity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.Donor'),
        ),
    ]
