# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20171020_0028'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Donor Media',
            },
        ),
        migrations.AlterModelOptions(
            name='productmedium',
            options={'verbose_name_plural': 'Product Media'},
        ),
        migrations.RemoveField(
            model_name='donor',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='video',
        ),
        migrations.AddField(
            model_name='donormedium',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Donor'),
        ),
        migrations.AddField(
            model_name='donormedium',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Medium'),
        ),
    ]
