# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20171027_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='website',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
