# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_charity_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='website',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
