# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20171023_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagging',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tagging',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Tagging',
        ),
    ]
