# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_donor_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='charge_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='hs_tariff_code',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('oz', 'oz'), ('lb', 'lb'), ('kg', 'kg'), ('g', 'g')], default='kg', max_length=10),
        ),
    ]
