# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_auto_20171207_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='charity',
        ),
    ]
