# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_remove_donor_charity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='description',
        ),
        migrations.AddField(
            model_name='charity',
            name='address',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charity',
            name='contact',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charity',
            name='phone',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
