# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=50)),
                ('mimetype', models.CharField(max_length=30)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Media',
            },
        ),
    ]
