# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='embed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medium',
            name='mimetype',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medium',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('embed', 'Embed')], max_length=50),
        ),
    ]
