# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medium',
            options={'verbose_name_plural': 'Media'},
        ),
    ]
