# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20171027_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
    ]
