# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20171027_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
