# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:04
from __future__ import unicode_literals

from django.db import migrations, models


def forwards(apps, schema_editor):
    Medium = apps.get_model('storage', 'Medium')
    Medium.objects.filter(type='photo').update(type='image')


def backwards(apps, schema_editor):
    Medium = apps.get_model('storage', 'Medium')
    Medium.objects.filter(type='image').update(type='photo')


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_medium_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=50),
        ),
        migrations.RunPython(forwards, backwards)
    ]
