NOTIFICATION_TYPE_AUCTION = 'auction'
NOTIFICATION_AUCTION_NEW = '{}/new'.format(NOTIFICATION_TYPE_AUCTION)
NOTIFICATION_AUCTION_NEW_BID = '{}/new-bid'.format(NOTIFICATION_TYPE_AUCTION)
NOTIFICATION_AUCTION_CLOSE = '{}/close'.format(NOTIFICATION_TYPE_AUCTION)
NOTIFICATION_AUCTION_PAYMENT = '{}/payment'.format(NOTIFICATION_TYPE_AUCTION)

NOTIFICATION_CONTENT_CHOICES = (
    (NOTIFICATION_AUCTION_NEW, 'New auction'),
    (NOTIFICATION_AUCTION_NEW_BID, 'New bid'),
    (NOTIFICATION_AUCTION_CLOSE, 'Auction closed'),
    (NOTIFICATION_AUCTION_PAYMENT, 'Payment on auction'),
)

WS_CHANNEL_AUCTION = 'auction'
