# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171015_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
