# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userverification_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
