# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
