export const AUTH_SIGNIN = 'charibin/auth/signin'
export const AUTH_SIGNOUT = 'charibin/auth/signout'
export const AUTH_SIGNUP = 'charibin/auth/signup'
export const AUTH_VERIFY_SIGNUP = 'charibin/auth/verify-signup'
export const AUTH_VERIFY_SIGNUP_RESET = 'charibin/auth/verify-signup-reset'
export const AUTH_CURRENT_USER = 'charibin/auth/current-user'
