export const AUTH_SIGNIN = 'charibin/auth/signin'
export const AUTH_SIGNOUT = 'charibin/auth/signout'
export const AUTH_SIGNUP = 'charibin/auth/signup'
export const AUTH_SIGNUP_WITH_FACEBOOK = 'charibin/auth/signup-with-facebook'
export const AUTH_VERIFY_SIGNUP = 'charibin/auth/verify-signup'
export const AUTH_VERIFY_SIGNUP_RESET = 'charibin/auth/verify-signup-reset'
export const AUTH_CURRENT_USER = 'charibin/auth/current-user'
export const AUTH_CURRENT_USER_UPDATE = 'charibin/auth/current-user/update'

export const ADMIN_GET_CHARITY_LIST = 'charibin/admin/get-charity-list'
export const ADMIN_CREATE_CHARITY = 'charibin/admin/create-charity'
export const ADMIN_GET_CHARITY_DETAIL = 'charibin/admin/get-charity-detail'
export const ADMIN_UPDATE_CHARITY_DETAIL = 'charibin/admin/update-charity-detail'
export const ADMIN_UPLOAD_CHARITY_LOGO = 'charibin/admin/upload-charity-logo'
export const ADMIN_DELETE_CHARITY = 'charibin/admin/delete-charity'
