# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 16:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('auction/new', 'New auction'), ('auction/new-bid', 'New bid'), ('auction/close', 'Auction closed'), ('auction/payment', 'Payment on auction')], max_length=50)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'NotificationEntities',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='notification.NotificationEntity'),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='notification.NotificationEntity'),
        ),
    ]
