# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='object',
        ),
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='notification.NotificationEntity'),
            preserve_default=False,
        ),
    ]
