DONOR_TYPE_COMPANY = 'company'
DONOR_TYPE_CELEBRITY = 'celebrity'
DONOR_TYPE_OTHER = 'other'

DONOR_TYPE_CHOICES = (
    (DONOR_TYPE_COMPANY, 'Company'),
    (DONOR_TYPE_CELEBRITY, 'Celebrity'),
    (DONOR_TYPE_OTHER, 'Other'),
)

MEDIUM_TYPE_PHOTO = 'photo'
MEDIUM_TYPE_VIDEO = 'video'

MEDIUM_TYPE_CHOICES = (
    (MEDIUM_TYPE_PHOTO, 'Photo'),
    (MEDIUM_TYPE_VIDEO, 'Video'),
)
