DONOR_TYPE_COMPANY = 'company'
DONOR_TYPE_CELEBRITY = 'celebrity'
DONOR_TYPE_OTHER = 'other'

DONOR_TYPE_CHOICES = (
    (DONOR_TYPE_COMPANY, 'Company'),
    (DONOR_TYPE_CELEBRITY, 'Celebrity'),
    (DONOR_TYPE_OTHER, 'Other'),
)

PRODUCT_WEIGHT_UNIT_OUNCE = 'oz'
PRODUCT_WEIGHT_UNIT_POUND = 'lb'
PRODUCT_WEIGHT_UNIT_KG = 'kg'
PRODUCT_WEIGHT_UNIT_GRAM = 'g'

PRODUCT_WEIGHT_UNIT_CHOICES = (
    (PRODUCT_WEIGHT_UNIT_OUNCE, 'oz'),
    (PRODUCT_WEIGHT_UNIT_POUND, 'lb'),
    (PRODUCT_WEIGHT_UNIT_KG, 'kg'),
    (PRODUCT_WEIGHT_UNIT_GRAM, 'g'),
)
